package com.lt.dao.model;

public class AdAd {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_ad.id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_ad.ad_group_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    private Integer adGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_ad.name
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_ad.note
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_ad.company_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_ad.id
     *
     * @return the value of lt_ad_ad.id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_ad.id
     *
     * @param id the value for lt_ad_ad.id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_ad.ad_group_id
     *
     * @return the value of lt_ad_ad.ad_group_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public Integer getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_ad.ad_group_id
     *
     * @param adGroupId the value for lt_ad_ad.ad_group_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public void setAdGroupId(Integer adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_ad.name
     *
     * @return the value of lt_ad_ad.name
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_ad.name
     *
     * @param name the value for lt_ad_ad.name
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_ad.note
     *
     * @return the value of lt_ad_ad.note
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_ad.note
     *
     * @param note the value for lt_ad_ad.note
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_ad.company_id
     *
     * @return the value of lt_ad_ad.company_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_ad.company_id
     *
     * @param companyId the value for lt_ad_ad.company_id
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}