package com.lt.dao.model;

import com.lt.platform.framework.core.model.MyBatisSuperModel;

public class AdChangeLog extends MyBatisSuperModel {
	public static final int STATUS_PENDING = 0;//等待处理
	public static final int STATUS_PROCESSED = 1;//已处理
	public static final int STATUS_PROCESS_FAILED = 2;//处理出错
	
	public static final int ACTION_ADDNEW = 0;//新增
	public static final int ACTION_UPDATE = 1;//修改
	public static final int ACTION_DELETE = 2;//删除
	
	public static final int PRIORITY_NORMAL = 0;//一般
	public static final int PRIORITY_HIGH = 1;//高
	public static final int PRIORITY_HIGHER = 2;//比较高
	public static final int PRIORITY_HIGHEST = 3;//最高
	public static final int PRIORITY_URGENT = 4;//紧急
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.company_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.object_type
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private String objectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.object_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer objectId;
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.action
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.status
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.priority
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.create_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.create_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.update_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.update_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_change_log.content
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.id
     *
     * @return the value of lt_ad_change_log.id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.id
     *
     * @param id the value for lt_ad_change_log.id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.company_id
     *
     * @return the value of lt_ad_change_log.company_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.company_id
     *
     * @param companyId the value for lt_ad_change_log.company_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.object_type
     *
     * @return the value of lt_ad_change_log.object_type
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.object_type
     *
     * @param objectType the value for lt_ad_change_log.object_type
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.object_id
     *
     * @return the value of lt_ad_change_log.object_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.object_id
     *
     * @param objectId the value for lt_ad_change_log.object_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.action
     *
     * @return the value of lt_ad_change_log.action
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.action
     *
     * @param action the value for lt_ad_change_log.action
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.status
     *
     * @return the value of lt_ad_change_log.status
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.status
     *
     * @param status the value for lt_ad_change_log.status
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.priority
     *
     * @return the value of lt_ad_change_log.priority
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.priority
     *
     * @param priority the value for lt_ad_change_log.priority
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.create_time_utc
     *
     * @return the value of lt_ad_change_log.create_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.create_time_utc
     *
     * @param createTimeUtc the value for lt_ad_change_log.create_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.create_user_id
     *
     * @return the value of lt_ad_change_log.create_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.create_user_id
     *
     * @param createUserId the value for lt_ad_change_log.create_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.update_time_utc
     *
     * @return the value of lt_ad_change_log.update_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.update_time_utc
     *
     * @param updateTimeUtc the value for lt_ad_change_log.update_time_utc
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.update_user_id
     *
     * @return the value of lt_ad_change_log.update_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.update_user_id
     *
     * @param updateUserId the value for lt_ad_change_log.update_user_id
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_change_log.content
     *
     * @return the value of lt_ad_change_log.content
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_change_log.content
     *
     * @param content the value for lt_ad_change_log.content
     *
     * @mbggenerated Tue Apr 14 18:15:36 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle()
    {
        return title;
    }

    public void setTitle(String title)
    {
        this.title = title;
    }
}