package com.lt.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class AdFacebookReportCampaign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private String campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private String campaignName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private String placement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Integer impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal cpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Integer clicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal ctr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal cpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.markup_type
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Byte markupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.markup_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal markupAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.charge_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private BigDecimal chargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.lt_ad_campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Integer ltAdCampaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_facebook_report_campaign.is_charged
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    private Boolean isCharged;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.date
     *
     * @return the value of lt_ad_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.date
     *
     * @param date the value for lt_ad_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.campaign_id
     *
     * @return the value of lt_ad_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.campaign_id
     *
     * @param campaignId the value for lt_ad_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCampaignId(String campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.campaign_name
     *
     * @return the value of lt_ad_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public String getCampaignName() {
        return campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.campaign_name
     *
     * @param campaignName the value for lt_ad_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.placement
     *
     * @return the value of lt_ad_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public String getPlacement() {
        return placement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.placement
     *
     * @param placement the value for lt_ad_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setPlacement(String placement) {
        this.placement = placement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.impressions
     *
     * @return the value of lt_ad_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Integer getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.impressions
     *
     * @param impressions the value for lt_ad_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setImpressions(Integer impressions) {
        this.impressions = impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.cpm
     *
     * @return the value of lt_ad_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getCpm() {
        return cpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.cpm
     *
     * @param cpm the value for lt_ad_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCpm(BigDecimal cpm) {
        this.cpm = cpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.clicks
     *
     * @return the value of lt_ad_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.clicks
     *
     * @param clicks the value for lt_ad_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.ctr
     *
     * @return the value of lt_ad_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getCtr() {
        return ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.ctr
     *
     * @param ctr the value for lt_ad_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCtr(BigDecimal ctr) {
        this.ctr = ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.cpc
     *
     * @return the value of lt_ad_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getCpc() {
        return cpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.cpc
     *
     * @param cpc the value for lt_ad_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCpc(BigDecimal cpc) {
        this.cpc = cpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.cost
     *
     * @return the value of lt_ad_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.cost
     *
     * @param cost the value for lt_ad_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.markup_type
     *
     * @return the value of lt_ad_facebook_report_campaign.markup_type
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Byte getMarkupType() {
        return markupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.markup_type
     *
     * @param markupType the value for lt_ad_facebook_report_campaign.markup_type
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setMarkupType(Byte markupType) {
        this.markupType = markupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.markup_amount
     *
     * @return the value of lt_ad_facebook_report_campaign.markup_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getMarkupAmount() {
        return markupAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.markup_amount
     *
     * @param markupAmount the value for lt_ad_facebook_report_campaign.markup_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setMarkupAmount(BigDecimal markupAmount) {
        this.markupAmount = markupAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.charge_amount
     *
     * @return the value of lt_ad_facebook_report_campaign.charge_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public BigDecimal getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.charge_amount
     *
     * @param chargeAmount the value for lt_ad_facebook_report_campaign.charge_amount
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.lt_ad_campaign_id
     *
     * @return the value of lt_ad_facebook_report_campaign.lt_ad_campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Integer getLtAdCampaignId() {
        return ltAdCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.lt_ad_campaign_id
     *
     * @param ltAdCampaignId the value for lt_ad_facebook_report_campaign.lt_ad_campaign_id
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setLtAdCampaignId(Integer ltAdCampaignId) {
        this.ltAdCampaignId = ltAdCampaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_facebook_report_campaign.is_charged
     *
     * @return the value of lt_ad_facebook_report_campaign.is_charged
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public Boolean getIsCharged() {
        return isCharged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_facebook_report_campaign.is_charged
     *
     * @param isCharged the value for lt_ad_facebook_report_campaign.is_charged
     *
     * @mbggenerated Tue Aug 25 17:15:41 CST 2015
     */
    public void setIsCharged(Boolean isCharged) {
        this.isCharged = isCharged;
    }
}