package com.lt.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class AdGoogleAdwordsReportDestinationUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.account_currency_code
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String accountCurrencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.account_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String accountDescriptiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.account_time_zone_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String accountTimeZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.active_view_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal activeViewCpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.active_view_impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer activeViewImpressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Long adGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ad_group_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String adGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ad_group_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String adGroupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ad_network_type1
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String adNetworkType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ad_network_type2
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String adNetworkType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.average_cpc
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal averageCpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.average_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal averageCpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.average_position
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double averagePosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.campaign_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Long campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.campaign_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String campaignName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.campaign_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String campaignStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.click_conversion_rate
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double clickConversionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.click_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String clickType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer clicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversion_category_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String conversionCategoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversion_rate_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double conversionRateManyPerClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversion_tracker_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Long conversionTrackerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversion_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String conversionTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversion_value
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double conversionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.conversions_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer conversionsManyPerClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.converted_clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer convertedClicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.cost
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.cost_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal costPerConversionManyPerClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.cost_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal costPerConvertedClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.criteria_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String criteriaDestinationUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.criteria_parameters
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String criteriaParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.criteria_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String criteriaStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.criteria_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String criteriaTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.ctr
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double ctr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.customer_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String customerDescriptiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.date
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.day_of_week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String dayOfWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.device
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.effective_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String effectiveDestinationUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.external_customer_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Long externalCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.is_negative
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String isNegative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.month
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.month_of_year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String monthOfYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.primary_company_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String primaryCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.quarter
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String quarter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.value_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double valuePerConversionManyPerClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.value_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Double valuePerConvertedClick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.view_through_conversions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer viewThroughConversions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.markup_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Byte markupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.markup_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal markupAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.charge_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private BigDecimal chargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.is_charged
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer isCharged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.lt_ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private Integer ltAdGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ad_google_adwords_report_destination_url.slot
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    private String slot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.account_currency_code
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.account_currency_code
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAccountCurrencyCode() {
        return accountCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.account_currency_code
     *
     * @param accountCurrencyCode the value for lt_ad_google_adwords_report_destination_url.account_currency_code
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAccountCurrencyCode(String accountCurrencyCode) {
        this.accountCurrencyCode = accountCurrencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.account_descriptive_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.account_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAccountDescriptiveName() {
        return accountDescriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.account_descriptive_name
     *
     * @param accountDescriptiveName the value for lt_ad_google_adwords_report_destination_url.account_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAccountDescriptiveName(String accountDescriptiveName) {
        this.accountDescriptiveName = accountDescriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.account_time_zone_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.account_time_zone_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAccountTimeZoneId() {
        return accountTimeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.account_time_zone_id
     *
     * @param accountTimeZoneId the value for lt_ad_google_adwords_report_destination_url.account_time_zone_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAccountTimeZoneId(String accountTimeZoneId) {
        this.accountTimeZoneId = accountTimeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.active_view_cpm
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.active_view_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getActiveViewCpm() {
        return activeViewCpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.active_view_cpm
     *
     * @param activeViewCpm the value for lt_ad_google_adwords_report_destination_url.active_view_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setActiveViewCpm(BigDecimal activeViewCpm) {
        this.activeViewCpm = activeViewCpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.active_view_impressions
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.active_view_impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getActiveViewImpressions() {
        return activeViewImpressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.active_view_impressions
     *
     * @param activeViewImpressions the value for lt_ad_google_adwords_report_destination_url.active_view_impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setActiveViewImpressions(Integer activeViewImpressions) {
        this.activeViewImpressions = activeViewImpressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Long getAdGroupId() {
        return adGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_id
     *
     * @param adGroupId the value for lt_ad_google_adwords_report_destination_url.ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAdGroupId(Long adGroupId) {
        this.adGroupId = adGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ad_group_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAdGroupName() {
        return adGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_name
     *
     * @param adGroupName the value for lt_ad_google_adwords_report_destination_url.ad_group_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAdGroupName(String adGroupName) {
        this.adGroupName = adGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_status
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ad_group_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAdGroupStatus() {
        return adGroupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ad_group_status
     *
     * @param adGroupStatus the value for lt_ad_google_adwords_report_destination_url.ad_group_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAdGroupStatus(String adGroupStatus) {
        this.adGroupStatus = adGroupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ad_network_type1
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ad_network_type1
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAdNetworkType1() {
        return adNetworkType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ad_network_type1
     *
     * @param adNetworkType1 the value for lt_ad_google_adwords_report_destination_url.ad_network_type1
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAdNetworkType1(String adNetworkType1) {
        this.adNetworkType1 = adNetworkType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ad_network_type2
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ad_network_type2
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getAdNetworkType2() {
        return adNetworkType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ad_network_type2
     *
     * @param adNetworkType2 the value for lt_ad_google_adwords_report_destination_url.ad_network_type2
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAdNetworkType2(String adNetworkType2) {
        this.adNetworkType2 = adNetworkType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.average_cpc
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.average_cpc
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getAverageCpc() {
        return averageCpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.average_cpc
     *
     * @param averageCpc the value for lt_ad_google_adwords_report_destination_url.average_cpc
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAverageCpc(BigDecimal averageCpc) {
        this.averageCpc = averageCpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.average_cpm
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.average_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getAverageCpm() {
        return averageCpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.average_cpm
     *
     * @param averageCpm the value for lt_ad_google_adwords_report_destination_url.average_cpm
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAverageCpm(BigDecimal averageCpm) {
        this.averageCpm = averageCpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.average_position
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.average_position
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getAveragePosition() {
        return averagePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.average_position
     *
     * @param averagePosition the value for lt_ad_google_adwords_report_destination_url.average_position
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setAveragePosition(Double averagePosition) {
        this.averagePosition = averagePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.campaign_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.campaign_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Long getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.campaign_id
     *
     * @param campaignId the value for lt_ad_google_adwords_report_destination_url.campaign_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCampaignId(Long campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.campaign_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.campaign_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCampaignName() {
        return campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.campaign_name
     *
     * @param campaignName the value for lt_ad_google_adwords_report_destination_url.campaign_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.campaign_status
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.campaign_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCampaignStatus() {
        return campaignStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.campaign_status
     *
     * @param campaignStatus the value for lt_ad_google_adwords_report_destination_url.campaign_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCampaignStatus(String campaignStatus) {
        this.campaignStatus = campaignStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.click_conversion_rate
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.click_conversion_rate
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getClickConversionRate() {
        return clickConversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.click_conversion_rate
     *
     * @param clickConversionRate the value for lt_ad_google_adwords_report_destination_url.click_conversion_rate
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setClickConversionRate(Double clickConversionRate) {
        this.clickConversionRate = clickConversionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.click_type
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.click_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getClickType() {
        return clickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.click_type
     *
     * @param clickType the value for lt_ad_google_adwords_report_destination_url.click_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setClickType(String clickType) {
        this.clickType = clickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.clicks
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.clicks
     *
     * @param clicks the value for lt_ad_google_adwords_report_destination_url.clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversion_category_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversion_category_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getConversionCategoryName() {
        return conversionCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversion_category_name
     *
     * @param conversionCategoryName the value for lt_ad_google_adwords_report_destination_url.conversion_category_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionCategoryName(String conversionCategoryName) {
        this.conversionCategoryName = conversionCategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversion_rate_many_per_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversion_rate_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getConversionRateManyPerClick() {
        return conversionRateManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversion_rate_many_per_click
     *
     * @param conversionRateManyPerClick the value for lt_ad_google_adwords_report_destination_url.conversion_rate_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionRateManyPerClick(Double conversionRateManyPerClick) {
        this.conversionRateManyPerClick = conversionRateManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversion_tracker_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversion_tracker_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Long getConversionTrackerId() {
        return conversionTrackerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversion_tracker_id
     *
     * @param conversionTrackerId the value for lt_ad_google_adwords_report_destination_url.conversion_tracker_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionTrackerId(Long conversionTrackerId) {
        this.conversionTrackerId = conversionTrackerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversion_type_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversion_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getConversionTypeName() {
        return conversionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversion_type_name
     *
     * @param conversionTypeName the value for lt_ad_google_adwords_report_destination_url.conversion_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionTypeName(String conversionTypeName) {
        this.conversionTypeName = conversionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversion_value
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversion_value
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getConversionValue() {
        return conversionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversion_value
     *
     * @param conversionValue the value for lt_ad_google_adwords_report_destination_url.conversion_value
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionValue(Double conversionValue) {
        this.conversionValue = conversionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.conversions_many_per_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.conversions_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getConversionsManyPerClick() {
        return conversionsManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.conversions_many_per_click
     *
     * @param conversionsManyPerClick the value for lt_ad_google_adwords_report_destination_url.conversions_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConversionsManyPerClick(Integer conversionsManyPerClick) {
        this.conversionsManyPerClick = conversionsManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.converted_clicks
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.converted_clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getConvertedClicks() {
        return convertedClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.converted_clicks
     *
     * @param convertedClicks the value for lt_ad_google_adwords_report_destination_url.converted_clicks
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setConvertedClicks(Integer convertedClicks) {
        this.convertedClicks = convertedClicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.cost
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.cost
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.cost
     *
     * @param cost the value for lt_ad_google_adwords_report_destination_url.cost
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCost(String cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.cost_per_conversion_many_per_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.cost_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getCostPerConversionManyPerClick() {
        return costPerConversionManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.cost_per_conversion_many_per_click
     *
     * @param costPerConversionManyPerClick the value for lt_ad_google_adwords_report_destination_url.cost_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCostPerConversionManyPerClick(BigDecimal costPerConversionManyPerClick) {
        this.costPerConversionManyPerClick = costPerConversionManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.cost_per_converted_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.cost_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getCostPerConvertedClick() {
        return costPerConvertedClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.cost_per_converted_click
     *
     * @param costPerConvertedClick the value for lt_ad_google_adwords_report_destination_url.cost_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCostPerConvertedClick(BigDecimal costPerConvertedClick) {
        this.costPerConvertedClick = costPerConvertedClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.criteria_destination_url
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.criteria_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCriteriaDestinationUrl() {
        return criteriaDestinationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.criteria_destination_url
     *
     * @param criteriaDestinationUrl the value for lt_ad_google_adwords_report_destination_url.criteria_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCriteriaDestinationUrl(String criteriaDestinationUrl) {
        this.criteriaDestinationUrl = criteriaDestinationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.criteria_parameters
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.criteria_parameters
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCriteriaParameters() {
        return criteriaParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.criteria_parameters
     *
     * @param criteriaParameters the value for lt_ad_google_adwords_report_destination_url.criteria_parameters
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCriteriaParameters(String criteriaParameters) {
        this.criteriaParameters = criteriaParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.criteria_status
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.criteria_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCriteriaStatus() {
        return criteriaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.criteria_status
     *
     * @param criteriaStatus the value for lt_ad_google_adwords_report_destination_url.criteria_status
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCriteriaStatus(String criteriaStatus) {
        this.criteriaStatus = criteriaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.criteria_type_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.criteria_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCriteriaTypeName() {
        return criteriaTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.criteria_type_name
     *
     * @param criteriaTypeName the value for lt_ad_google_adwords_report_destination_url.criteria_type_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCriteriaTypeName(String criteriaTypeName) {
        this.criteriaTypeName = criteriaTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.ctr
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.ctr
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getCtr() {
        return ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.ctr
     *
     * @param ctr the value for lt_ad_google_adwords_report_destination_url.ctr
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCtr(Double ctr) {
        this.ctr = ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.customer_descriptive_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.customer_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getCustomerDescriptiveName() {
        return customerDescriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.customer_descriptive_name
     *
     * @param customerDescriptiveName the value for lt_ad_google_adwords_report_destination_url.customer_descriptive_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setCustomerDescriptiveName(String customerDescriptiveName) {
        this.customerDescriptiveName = customerDescriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.date
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.date
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.date
     *
     * @param date the value for lt_ad_google_adwords_report_destination_url.date
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.day_of_week
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.day_of_week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.day_of_week
     *
     * @param dayOfWeek the value for lt_ad_google_adwords_report_destination_url.day_of_week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.device
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.device
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.device
     *
     * @param device the value for lt_ad_google_adwords_report_destination_url.device
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setDevice(String device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.effective_destination_url
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.effective_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getEffectiveDestinationUrl() {
        return effectiveDestinationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.effective_destination_url
     *
     * @param effectiveDestinationUrl the value for lt_ad_google_adwords_report_destination_url.effective_destination_url
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setEffectiveDestinationUrl(String effectiveDestinationUrl) {
        this.effectiveDestinationUrl = effectiveDestinationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.external_customer_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.external_customer_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Long getExternalCustomerId() {
        return externalCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.external_customer_id
     *
     * @param externalCustomerId the value for lt_ad_google_adwords_report_destination_url.external_customer_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setExternalCustomerId(Long externalCustomerId) {
        this.externalCustomerId = externalCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.impressions
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.impressions
     *
     * @param impressions the value for lt_ad_google_adwords_report_destination_url.impressions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setImpressions(Integer impressions) {
        this.impressions = impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.is_negative
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.is_negative
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getIsNegative() {
        return isNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.is_negative
     *
     * @param isNegative the value for lt_ad_google_adwords_report_destination_url.is_negative
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setIsNegative(String isNegative) {
        this.isNegative = isNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.month
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.month
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.month
     *
     * @param month the value for lt_ad_google_adwords_report_destination_url.month
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.month_of_year
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.month_of_year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getMonthOfYear() {
        return monthOfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.month_of_year
     *
     * @param monthOfYear the value for lt_ad_google_adwords_report_destination_url.month_of_year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setMonthOfYear(String monthOfYear) {
        this.monthOfYear = monthOfYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.primary_company_name
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.primary_company_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getPrimaryCompanyName() {
        return primaryCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.primary_company_name
     *
     * @param primaryCompanyName the value for lt_ad_google_adwords_report_destination_url.primary_company_name
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setPrimaryCompanyName(String primaryCompanyName) {
        this.primaryCompanyName = primaryCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.quarter
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.quarter
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getQuarter() {
        return quarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.quarter
     *
     * @param quarter the value for lt_ad_google_adwords_report_destination_url.quarter
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setQuarter(String quarter) {
        this.quarter = quarter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.value_per_conversion_many_per_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.value_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getValuePerConversionManyPerClick() {
        return valuePerConversionManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.value_per_conversion_many_per_click
     *
     * @param valuePerConversionManyPerClick the value for lt_ad_google_adwords_report_destination_url.value_per_conversion_many_per_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setValuePerConversionManyPerClick(Double valuePerConversionManyPerClick) {
        this.valuePerConversionManyPerClick = valuePerConversionManyPerClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.value_per_converted_click
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.value_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Double getValuePerConvertedClick() {
        return valuePerConvertedClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.value_per_converted_click
     *
     * @param valuePerConvertedClick the value for lt_ad_google_adwords_report_destination_url.value_per_converted_click
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setValuePerConvertedClick(Double valuePerConvertedClick) {
        this.valuePerConvertedClick = valuePerConvertedClick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.view_through_conversions
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.view_through_conversions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getViewThroughConversions() {
        return viewThroughConversions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.view_through_conversions
     *
     * @param viewThroughConversions the value for lt_ad_google_adwords_report_destination_url.view_through_conversions
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setViewThroughConversions(Integer viewThroughConversions) {
        this.viewThroughConversions = viewThroughConversions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.week
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.week
     *
     * @param week the value for lt_ad_google_adwords_report_destination_url.week
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setWeek(String week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.year
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.year
     *
     * @param year the value for lt_ad_google_adwords_report_destination_url.year
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.markup_type
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.markup_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Byte getMarkupType() {
        return markupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.markup_type
     *
     * @param markupType the value for lt_ad_google_adwords_report_destination_url.markup_type
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setMarkupType(Byte markupType) {
        this.markupType = markupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.markup_amount
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.markup_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getMarkupAmount() {
        return markupAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.markup_amount
     *
     * @param markupAmount the value for lt_ad_google_adwords_report_destination_url.markup_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setMarkupAmount(BigDecimal markupAmount) {
        this.markupAmount = markupAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.charge_amount
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.charge_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public BigDecimal getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.charge_amount
     *
     * @param chargeAmount the value for lt_ad_google_adwords_report_destination_url.charge_amount
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.is_charged
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.is_charged
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getIsCharged() {
        return isCharged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.is_charged
     *
     * @param isCharged the value for lt_ad_google_adwords_report_destination_url.is_charged
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setIsCharged(Integer isCharged) {
        this.isCharged = isCharged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.lt_ad_group_id
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.lt_ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public Integer getLtAdGroupId() {
        return ltAdGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.lt_ad_group_id
     *
     * @param ltAdGroupId the value for lt_ad_google_adwords_report_destination_url.lt_ad_group_id
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setLtAdGroupId(Integer ltAdGroupId) {
        this.ltAdGroupId = ltAdGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ad_google_adwords_report_destination_url.slot
     *
     * @return the value of lt_ad_google_adwords_report_destination_url.slot
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ad_google_adwords_report_destination_url.slot
     *
     * @param slot the value for lt_ad_google_adwords_report_destination_url.slot
     *
     * @mbggenerated Fri May 29 15:08:32 CST 2015
     */
    public void setSlot(String slot) {
        this.slot = slot;
    }
}