package com.lt.dao.model;

public class AuthItemChildKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_AuthItemChild.parent
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_AuthItemChild.child
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String child;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_AuthItemChild.parent
     *
     * @return the value of lt_AuthItemChild.parent
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_AuthItemChild.parent
     *
     * @param parent the value for lt_AuthItemChild.parent
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setParent(String parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_AuthItemChild.child
     *
     * @return the value of lt_AuthItemChild.child
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_AuthItemChild.child
     *
     * @param child the value for lt_AuthItemChild.child
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setChild(String child) {
        this.child = child;
    }
}