package com.lt.dao.model;

public class EbayListing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.store_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.ebay_listing_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String ebayListingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebayEntityTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebayAttributeSetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Byte isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_listing.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.id
     *
     * @return the value of lt_ebay_listing.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.id
     *
     * @param id the value for lt_ebay_listing.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.store_id
     *
     * @return the value of lt_ebay_listing.store_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.store_id
     *
     * @param storeId the value for lt_ebay_listing.store_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.company_id
     *
     * @return the value of lt_ebay_listing.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.company_id
     *
     * @param companyId the value for lt_ebay_listing.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.ebay_listing_id
     *
     * @return the value of lt_ebay_listing.ebay_listing_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getEbayListingId() {
        return ebayListingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.ebay_listing_id
     *
     * @param ebayListingId the value for lt_ebay_listing.ebay_listing_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayListingId(String ebayListingId) {
        this.ebayListingId = ebayListingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.site_id
     *
     * @return the value of lt_ebay_listing.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.site_id
     *
     * @param siteId the value for lt_ebay_listing.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.ebay_entity_type_id
     *
     * @return the value of lt_ebay_listing.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbayEntityTypeId() {
        return ebayEntityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.ebay_entity_type_id
     *
     * @param ebayEntityTypeId the value for lt_ebay_listing.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayEntityTypeId(Integer ebayEntityTypeId) {
        this.ebayEntityTypeId = ebayEntityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.ebay_attribute_set_id
     *
     * @return the value of lt_ebay_listing.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbayAttributeSetId() {
        return ebayAttributeSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.ebay_attribute_set_id
     *
     * @param ebayAttributeSetId the value for lt_ebay_listing.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayAttributeSetId(Integer ebayAttributeSetId) {
        this.ebayAttributeSetId = ebayAttributeSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.is_active
     *
     * @return the value of lt_ebay_listing.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.is_active
     *
     * @param isActive the value for lt_ebay_listing.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.note
     *
     * @return the value of lt_ebay_listing.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.note
     *
     * @param note the value for lt_ebay_listing.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.create_time_utc
     *
     * @return the value of lt_ebay_listing.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.create_time_utc
     *
     * @param createTimeUtc the value for lt_ebay_listing.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.create_user_id
     *
     * @return the value of lt_ebay_listing.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.create_user_id
     *
     * @param createUserId the value for lt_ebay_listing.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.update_time_utc
     *
     * @return the value of lt_ebay_listing.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.update_time_utc
     *
     * @param updateTimeUtc the value for lt_ebay_listing.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_listing.update_user_id
     *
     * @return the value of lt_ebay_listing.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_listing.update_user_id
     *
     * @param updateUserId the value for lt_ebay_listing.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }
}