package com.lt.dao.model;

public class EbayCategoryFeatureDefinitionAndDefault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.CategoryVersion
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String categoryversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebayEntityTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebayAttributeSetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_category_feature_definition_and_default.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateAdminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.id
     *
     * @param id the value for lt_ebay_category_feature_definition_and_default.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.name
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.name
     *
     * @param name the value for lt_ebay_category_feature_definition_and_default.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.site_id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.site_id
     *
     * @param siteId the value for lt_ebay_category_feature_definition_and_default.site_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.CategoryVersion
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.CategoryVersion
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getCategoryversion() {
        return categoryversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.CategoryVersion
     *
     * @param categoryversion the value for lt_ebay_category_feature_definition_and_default.CategoryVersion
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCategoryversion(String categoryversion) {
        this.categoryversion = categoryversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.ebay_entity_type_id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbayEntityTypeId() {
        return ebayEntityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.ebay_entity_type_id
     *
     * @param ebayEntityTypeId the value for lt_ebay_category_feature_definition_and_default.ebay_entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayEntityTypeId(Integer ebayEntityTypeId) {
        this.ebayEntityTypeId = ebayEntityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.ebay_attribute_set_id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbayAttributeSetId() {
        return ebayAttributeSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.ebay_attribute_set_id
     *
     * @param ebayAttributeSetId the value for lt_ebay_category_feature_definition_and_default.ebay_attribute_set_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayAttributeSetId(Integer ebayAttributeSetId) {
        this.ebayAttributeSetId = ebayAttributeSetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.note
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.note
     *
     * @param note the value for lt_ebay_category_feature_definition_and_default.note
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.create_time_utc
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.create_time_utc
     *
     * @param createTimeUtc the value for lt_ebay_category_feature_definition_and_default.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.create_admin_id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.create_admin_id
     *
     * @param createAdminId the value for lt_ebay_category_feature_definition_and_default.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.update_time_utc
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.update_time_utc
     *
     * @param updateTimeUtc the value for lt_ebay_category_feature_definition_and_default.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_category_feature_definition_and_default.update_admin_id
     *
     * @return the value of lt_ebay_category_feature_definition_and_default.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_category_feature_definition_and_default.update_admin_id
     *
     * @param updateAdminId the value for lt_ebay_category_feature_definition_and_default.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateAdminId(Integer updateAdminId) {
        this.updateAdminId = updateAdminId;
    }
}