package com.lt.dao.model;

public class EbayAttributeSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer entityTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Byte isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.sort_order
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Short sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ebay_attribute_set.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateAdminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.id
     *
     * @return the value of lt_ebay_attribute_set.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.id
     *
     * @param id the value for lt_ebay_attribute_set.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.name
     *
     * @return the value of lt_ebay_attribute_set.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.name
     *
     * @param name the value for lt_ebay_attribute_set.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.entity_type_id
     *
     * @return the value of lt_ebay_attribute_set.entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEntityTypeId() {
        return entityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.entity_type_id
     *
     * @param entityTypeId the value for lt_ebay_attribute_set.entity_type_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEntityTypeId(Integer entityTypeId) {
        this.entityTypeId = entityTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.is_active
     *
     * @return the value of lt_ebay_attribute_set.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Byte getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.is_active
     *
     * @param isActive the value for lt_ebay_attribute_set.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.sort_order
     *
     * @return the value of lt_ebay_attribute_set.sort_order
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Short getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.sort_order
     *
     * @param sortOrder the value for lt_ebay_attribute_set.sort_order
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setSortOrder(Short sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.create_time_utc
     *
     * @return the value of lt_ebay_attribute_set.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.create_time_utc
     *
     * @param createTimeUtc the value for lt_ebay_attribute_set.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.create_admin_id
     *
     * @return the value of lt_ebay_attribute_set.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.create_admin_id
     *
     * @param createAdminId the value for lt_ebay_attribute_set.create_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.update_time_utc
     *
     * @return the value of lt_ebay_attribute_set.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.update_time_utc
     *
     * @param updateTimeUtc the value for lt_ebay_attribute_set.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ebay_attribute_set.update_admin_id
     *
     * @return the value of lt_ebay_attribute_set.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ebay_attribute_set.update_admin_id
     *
     * @param updateAdminId the value for lt_ebay_attribute_set.update_admin_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateAdminId(Integer updateAdminId) {
        this.updateAdminId = updateAdminId;
    }
}