package com.lt.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class FacebookReportCampaign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private String campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private String campaignName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private String placement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private Integer impressions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private BigDecimal cpm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private Integer clicks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private BigDecimal ctr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private BigDecimal cpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    private BigDecimal cost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.date
     *
     * @return the value of lt_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.date
     *
     * @param date the value for lt_facebook_report_campaign.date
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.campaign_id
     *
     * @return the value of lt_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.campaign_id
     *
     * @param campaignId the value for lt_facebook_report_campaign.campaign_id
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCampaignId(String campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.campaign_name
     *
     * @return the value of lt_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public String getCampaignName() {
        return campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.campaign_name
     *
     * @param campaignName the value for lt_facebook_report_campaign.campaign_name
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.placement
     *
     * @return the value of lt_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public String getPlacement() {
        return placement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.placement
     *
     * @param placement the value for lt_facebook_report_campaign.placement
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setPlacement(String placement) {
        this.placement = placement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.impressions
     *
     * @return the value of lt_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public Integer getImpressions() {
        return impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.impressions
     *
     * @param impressions the value for lt_facebook_report_campaign.impressions
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setImpressions(Integer impressions) {
        this.impressions = impressions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.cpm
     *
     * @return the value of lt_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public BigDecimal getCpm() {
        return cpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.cpm
     *
     * @param cpm the value for lt_facebook_report_campaign.cpm
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCpm(BigDecimal cpm) {
        this.cpm = cpm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.clicks
     *
     * @return the value of lt_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public Integer getClicks() {
        return clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.clicks
     *
     * @param clicks the value for lt_facebook_report_campaign.clicks
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setClicks(Integer clicks) {
        this.clicks = clicks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.ctr
     *
     * @return the value of lt_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public BigDecimal getCtr() {
        return ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.ctr
     *
     * @param ctr the value for lt_facebook_report_campaign.ctr
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCtr(BigDecimal ctr) {
        this.ctr = ctr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.cpc
     *
     * @return the value of lt_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public BigDecimal getCpc() {
        return cpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.cpc
     *
     * @param cpc the value for lt_facebook_report_campaign.cpc
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCpc(BigDecimal cpc) {
        this.cpc = cpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_facebook_report_campaign.cost
     *
     * @return the value of lt_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_facebook_report_campaign.cost
     *
     * @param cost the value for lt_facebook_report_campaign.cost
     *
     * @mbggenerated Tue Aug 25 17:21:59 CST 2015
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
}