package com.lt.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class GoogleAnalyticsReportPagePath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.date
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.property
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private String page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.sessions
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Integer sessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.bounce_rate
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private BigDecimal bounceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private BigDecimal sessionDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.pageviews_per_session
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private BigDecimal pageviewsPerSession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.avg_time_on_page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private BigDecimal avgTimeOnPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.unique_pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Integer uniquePageviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.entrances
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Integer entrances;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Integer pageviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.exits
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private Integer exits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_page_path.avg_session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    private BigDecimal avgSessionDuration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.date
     *
     * @return the value of lt_google_analytics_report_page_path.date
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.date
     *
     * @param date the value for lt_google_analytics_report_page_path.date
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.property
     *
     * @return the value of lt_google_analytics_report_page_path.property
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.property
     *
     * @param property the value for lt_google_analytics_report_page_path.property
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setProperty(String property) {
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.page
     *
     * @return the value of lt_google_analytics_report_page_path.page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.page
     *
     * @param page the value for lt_google_analytics_report_page_path.page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.sessions
     *
     * @return the value of lt_google_analytics_report_page_path.sessions
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Integer getSessions() {
        return sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.sessions
     *
     * @param sessions the value for lt_google_analytics_report_page_path.sessions
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setSessions(Integer sessions) {
        this.sessions = sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.bounce_rate
     *
     * @return the value of lt_google_analytics_report_page_path.bounce_rate
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public BigDecimal getBounceRate() {
        return bounceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.bounce_rate
     *
     * @param bounceRate the value for lt_google_analytics_report_page_path.bounce_rate
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setBounceRate(BigDecimal bounceRate) {
        this.bounceRate = bounceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.session_duration
     *
     * @return the value of lt_google_analytics_report_page_path.session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public BigDecimal getSessionDuration() {
        return sessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.session_duration
     *
     * @param sessionDuration the value for lt_google_analytics_report_page_path.session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setSessionDuration(BigDecimal sessionDuration) {
        this.sessionDuration = sessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.pageviews_per_session
     *
     * @return the value of lt_google_analytics_report_page_path.pageviews_per_session
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public BigDecimal getPageviewsPerSession() {
        return pageviewsPerSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.pageviews_per_session
     *
     * @param pageviewsPerSession the value for lt_google_analytics_report_page_path.pageviews_per_session
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setPageviewsPerSession(BigDecimal pageviewsPerSession) {
        this.pageviewsPerSession = pageviewsPerSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.avg_time_on_page
     *
     * @return the value of lt_google_analytics_report_page_path.avg_time_on_page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public BigDecimal getAvgTimeOnPage() {
        return avgTimeOnPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.avg_time_on_page
     *
     * @param avgTimeOnPage the value for lt_google_analytics_report_page_path.avg_time_on_page
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setAvgTimeOnPage(BigDecimal avgTimeOnPage) {
        this.avgTimeOnPage = avgTimeOnPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.unique_pageviews
     *
     * @return the value of lt_google_analytics_report_page_path.unique_pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Integer getUniquePageviews() {
        return uniquePageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.unique_pageviews
     *
     * @param uniquePageviews the value for lt_google_analytics_report_page_path.unique_pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setUniquePageviews(Integer uniquePageviews) {
        this.uniquePageviews = uniquePageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.entrances
     *
     * @return the value of lt_google_analytics_report_page_path.entrances
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Integer getEntrances() {
        return entrances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.entrances
     *
     * @param entrances the value for lt_google_analytics_report_page_path.entrances
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setEntrances(Integer entrances) {
        this.entrances = entrances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.pageviews
     *
     * @return the value of lt_google_analytics_report_page_path.pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Integer getPageviews() {
        return pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.pageviews
     *
     * @param pageviews the value for lt_google_analytics_report_page_path.pageviews
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setPageviews(Integer pageviews) {
        this.pageviews = pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.exits
     *
     * @return the value of lt_google_analytics_report_page_path.exits
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public Integer getExits() {
        return exits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.exits
     *
     * @param exits the value for lt_google_analytics_report_page_path.exits
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setExits(Integer exits) {
        this.exits = exits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_page_path.avg_session_duration
     *
     * @return the value of lt_google_analytics_report_page_path.avg_session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public BigDecimal getAvgSessionDuration() {
        return avgSessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_page_path.avg_session_duration
     *
     * @param avgSessionDuration the value for lt_google_analytics_report_page_path.avg_session_duration
     *
     * @mbggenerated Thu Aug 20 10:01:08 CST 2015
     */
    public void setAvgSessionDuration(BigDecimal avgSessionDuration) {
        this.avgSessionDuration = avgSessionDuration;
    }
}