package com.lt.dao.model;

public class GoogleAdwordsAdGroupWithBLOBs extends GoogleAdwordsAdGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.settings
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String settings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.experiment_data
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String experimentData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.labels
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String labels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.forward_compatibility_map
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String forwardCompatibilityMap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.bidding_strategy_configuration
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String biddingStrategyConfiguration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.content_bid_criterionType_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String contentBidCriteriontypeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_ad_group.url_custom_parameters
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String urlCustomParameters;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.settings
     *
     * @return the value of lt_google_adwords_ad_group.settings
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getSettings() {
        return settings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.settings
     *
     * @param settings the value for lt_google_adwords_ad_group.settings
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setSettings(String settings) {
        this.settings = settings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.experiment_data
     *
     * @return the value of lt_google_adwords_ad_group.experiment_data
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getExperimentData() {
        return experimentData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.experiment_data
     *
     * @param experimentData the value for lt_google_adwords_ad_group.experiment_data
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setExperimentData(String experimentData) {
        this.experimentData = experimentData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.labels
     *
     * @return the value of lt_google_adwords_ad_group.labels
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.labels
     *
     * @param labels the value for lt_google_adwords_ad_group.labels
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setLabels(String labels) {
        this.labels = labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.forward_compatibility_map
     *
     * @return the value of lt_google_adwords_ad_group.forward_compatibility_map
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getForwardCompatibilityMap() {
        return forwardCompatibilityMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.forward_compatibility_map
     *
     * @param forwardCompatibilityMap the value for lt_google_adwords_ad_group.forward_compatibility_map
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setForwardCompatibilityMap(String forwardCompatibilityMap) {
        this.forwardCompatibilityMap = forwardCompatibilityMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.bidding_strategy_configuration
     *
     * @return the value of lt_google_adwords_ad_group.bidding_strategy_configuration
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getBiddingStrategyConfiguration() {
        return biddingStrategyConfiguration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.bidding_strategy_configuration
     *
     * @param biddingStrategyConfiguration the value for lt_google_adwords_ad_group.bidding_strategy_configuration
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setBiddingStrategyConfiguration(String biddingStrategyConfiguration) {
        this.biddingStrategyConfiguration = biddingStrategyConfiguration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.content_bid_criterionType_group
     *
     * @return the value of lt_google_adwords_ad_group.content_bid_criterionType_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getContentBidCriteriontypeGroup() {
        return contentBidCriteriontypeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.content_bid_criterionType_group
     *
     * @param contentBidCriteriontypeGroup the value for lt_google_adwords_ad_group.content_bid_criterionType_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setContentBidCriteriontypeGroup(String contentBidCriteriontypeGroup) {
        this.contentBidCriteriontypeGroup = contentBidCriteriontypeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_ad_group.url_custom_parameters
     *
     * @return the value of lt_google_adwords_ad_group.url_custom_parameters
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getUrlCustomParameters() {
        return urlCustomParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_ad_group.url_custom_parameters
     *
     * @param urlCustomParameters the value for lt_google_adwords_ad_group.url_custom_parameters
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setUrlCustomParameters(String urlCustomParameters) {
        this.urlCustomParameters = urlCustomParameters;
    }
}