package com.lt.dao.model;

public class GoogleAdwordsCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.customer_id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.currency_code
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.date_time_zone
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String dateTimeZone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.descriptive_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String descriptiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.company_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.can_manage_clients
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private Boolean canManageClients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.test_account
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private Boolean testAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.auto_tagging_enabled
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private Boolean autoTaggingEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_customer.tracking_url_template
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    private String trackingUrlTemplate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.id
     *
     * @return the value of lt_google_adwords_customer.id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.id
     *
     * @param id the value for lt_google_adwords_customer.id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.customer_id
     *
     * @return the value of lt_google_adwords_customer.customer_id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.customer_id
     *
     * @param customerId the value for lt_google_adwords_customer.customer_id
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.currency_code
     *
     * @return the value of lt_google_adwords_customer.currency_code
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.currency_code
     *
     * @param currencyCode the value for lt_google_adwords_customer.currency_code
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.date_time_zone
     *
     * @return the value of lt_google_adwords_customer.date_time_zone
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getDateTimeZone() {
        return dateTimeZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.date_time_zone
     *
     * @param dateTimeZone the value for lt_google_adwords_customer.date_time_zone
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setDateTimeZone(String dateTimeZone) {
        this.dateTimeZone = dateTimeZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.descriptive_name
     *
     * @return the value of lt_google_adwords_customer.descriptive_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getDescriptiveName() {
        return descriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.descriptive_name
     *
     * @param descriptiveName the value for lt_google_adwords_customer.descriptive_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setDescriptiveName(String descriptiveName) {
        this.descriptiveName = descriptiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.company_name
     *
     * @return the value of lt_google_adwords_customer.company_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.company_name
     *
     * @param companyName the value for lt_google_adwords_customer.company_name
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.can_manage_clients
     *
     * @return the value of lt_google_adwords_customer.can_manage_clients
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public Boolean getCanManageClients() {
        return canManageClients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.can_manage_clients
     *
     * @param canManageClients the value for lt_google_adwords_customer.can_manage_clients
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setCanManageClients(Boolean canManageClients) {
        this.canManageClients = canManageClients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.test_account
     *
     * @return the value of lt_google_adwords_customer.test_account
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public Boolean getTestAccount() {
        return testAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.test_account
     *
     * @param testAccount the value for lt_google_adwords_customer.test_account
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setTestAccount(Boolean testAccount) {
        this.testAccount = testAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.auto_tagging_enabled
     *
     * @return the value of lt_google_adwords_customer.auto_tagging_enabled
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public Boolean getAutoTaggingEnabled() {
        return autoTaggingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.auto_tagging_enabled
     *
     * @param autoTaggingEnabled the value for lt_google_adwords_customer.auto_tagging_enabled
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setAutoTaggingEnabled(Boolean autoTaggingEnabled) {
        this.autoTaggingEnabled = autoTaggingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_customer.tracking_url_template
     *
     * @return the value of lt_google_adwords_customer.tracking_url_template
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public String getTrackingUrlTemplate() {
        return trackingUrlTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_customer.tracking_url_template
     *
     * @param trackingUrlTemplate the value for lt_google_adwords_customer.tracking_url_template
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    public void setTrackingUrlTemplate(String trackingUrlTemplate) {
        this.trackingUrlTemplate = trackingUrlTemplate;
    }
}