package com.lt.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class GoogleAnalyticsReportAudienceOverview {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.date
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private Integer sessions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.users
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private Integer users;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.pageviews
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private Integer pageviews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.pageviews_per_session
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private BigDecimal pageviewsPerSession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.avg_session_duration
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private BigDecimal avgSessionDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.bounce_rate
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private BigDecimal bounceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_analytics_report_audience_overview.percent_new_sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    private BigDecimal percentNewSessions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.date
     *
     * @return the value of lt_google_analytics_report_audience_overview.date
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.date
     *
     * @param date the value for lt_google_analytics_report_audience_overview.date
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.sessions
     *
     * @return the value of lt_google_analytics_report_audience_overview.sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public Integer getSessions() {
        return sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.sessions
     *
     * @param sessions the value for lt_google_analytics_report_audience_overview.sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setSessions(Integer sessions) {
        this.sessions = sessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.users
     *
     * @return the value of lt_google_analytics_report_audience_overview.users
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public Integer getUsers() {
        return users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.users
     *
     * @param users the value for lt_google_analytics_report_audience_overview.users
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setUsers(Integer users) {
        this.users = users;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.pageviews
     *
     * @return the value of lt_google_analytics_report_audience_overview.pageviews
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public Integer getPageviews() {
        return pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.pageviews
     *
     * @param pageviews the value for lt_google_analytics_report_audience_overview.pageviews
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setPageviews(Integer pageviews) {
        this.pageviews = pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.pageviews_per_session
     *
     * @return the value of lt_google_analytics_report_audience_overview.pageviews_per_session
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public BigDecimal getPageviewsPerSession() {
        return pageviewsPerSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.pageviews_per_session
     *
     * @param pageviewsPerSession the value for lt_google_analytics_report_audience_overview.pageviews_per_session
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setPageviewsPerSession(BigDecimal pageviewsPerSession) {
        this.pageviewsPerSession = pageviewsPerSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.avg_session_duration
     *
     * @return the value of lt_google_analytics_report_audience_overview.avg_session_duration
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public BigDecimal getAvgSessionDuration() {
        return avgSessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.avg_session_duration
     *
     * @param avgSessionDuration the value for lt_google_analytics_report_audience_overview.avg_session_duration
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setAvgSessionDuration(BigDecimal avgSessionDuration) {
        this.avgSessionDuration = avgSessionDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.bounce_rate
     *
     * @return the value of lt_google_analytics_report_audience_overview.bounce_rate
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public BigDecimal getBounceRate() {
        return bounceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.bounce_rate
     *
     * @param bounceRate the value for lt_google_analytics_report_audience_overview.bounce_rate
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setBounceRate(BigDecimal bounceRate) {
        this.bounceRate = bounceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_analytics_report_audience_overview.percent_new_sessions
     *
     * @return the value of lt_google_analytics_report_audience_overview.percent_new_sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public BigDecimal getPercentNewSessions() {
        return percentNewSessions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_analytics_report_audience_overview.percent_new_sessions
     *
     * @param percentNewSessions the value for lt_google_analytics_report_audience_overview.percent_new_sessions
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    public void setPercentNewSessions(BigDecimal percentNewSessions) {
        this.percentNewSessions = percentNewSessions;
    }
}