package com.lt.dao.model;

public class GoogleAdwordsReportKeywordsWithBLOBs extends GoogleAdwordsReportKeywords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_report_keywords.final_app_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    private String finalAppUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_report_keywords.final_mobile_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    private String finalMobileUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_google_adwords_report_keywords.final_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    private String finalUrls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_report_keywords.final_app_urls
     *
     * @return the value of lt_google_adwords_report_keywords.final_app_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public String getFinalAppUrls() {
        return finalAppUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_report_keywords.final_app_urls
     *
     * @param finalAppUrls the value for lt_google_adwords_report_keywords.final_app_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public void setFinalAppUrls(String finalAppUrls) {
        this.finalAppUrls = finalAppUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_report_keywords.final_mobile_urls
     *
     * @return the value of lt_google_adwords_report_keywords.final_mobile_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public String getFinalMobileUrls() {
        return finalMobileUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_report_keywords.final_mobile_urls
     *
     * @param finalMobileUrls the value for lt_google_adwords_report_keywords.final_mobile_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public void setFinalMobileUrls(String finalMobileUrls) {
        this.finalMobileUrls = finalMobileUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_google_adwords_report_keywords.final_urls
     *
     * @return the value of lt_google_adwords_report_keywords.final_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public String getFinalUrls() {
        return finalUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_google_adwords_report_keywords.final_urls
     *
     * @param finalUrls the value for lt_google_adwords_report_keywords.final_urls
     *
     * @mbggenerated Fri Jun 19 16:31:03 CST 2015
     */
    public void setFinalUrls(String finalUrls) {
        this.finalUrls = finalUrls;
    }
}