package com.lt.dao.model;

public class ScheduleJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.action
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.last_execute_status
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer lastExecuteStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.last_execute_result
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String lastExecuteResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.last_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer lastExecuteTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.last_finish_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer lastFinishTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.next_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer nextExecuteTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.crontab
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String crontab;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.type
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_schedule_job.params
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.id
     *
     * @return the value of lt_schedule_job.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.id
     *
     * @param id the value for lt_schedule_job.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.platform
     *
     * @return the value of lt_schedule_job.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.platform
     *
     * @param platform the value for lt_schedule_job.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.action
     *
     * @return the value of lt_schedule_job.action
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.action
     *
     * @param action the value for lt_schedule_job.action
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.is_active
     *
     * @return the value of lt_schedule_job.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.is_active
     *
     * @param isActive the value for lt_schedule_job.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.create_time_utc
     *
     * @return the value of lt_schedule_job.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.create_time_utc
     *
     * @param createTimeUtc the value for lt_schedule_job.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.last_execute_status
     *
     * @return the value of lt_schedule_job.last_execute_status
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getLastExecuteStatus() {
        return lastExecuteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.last_execute_status
     *
     * @param lastExecuteStatus the value for lt_schedule_job.last_execute_status
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setLastExecuteStatus(Integer lastExecuteStatus) {
        this.lastExecuteStatus = lastExecuteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.last_execute_result
     *
     * @return the value of lt_schedule_job.last_execute_result
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getLastExecuteResult() {
        return lastExecuteResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.last_execute_result
     *
     * @param lastExecuteResult the value for lt_schedule_job.last_execute_result
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setLastExecuteResult(String lastExecuteResult) {
        this.lastExecuteResult = lastExecuteResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.last_execute_time_utc
     *
     * @return the value of lt_schedule_job.last_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getLastExecuteTimeUtc() {
        return lastExecuteTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.last_execute_time_utc
     *
     * @param lastExecuteTimeUtc the value for lt_schedule_job.last_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setLastExecuteTimeUtc(Integer lastExecuteTimeUtc) {
        this.lastExecuteTimeUtc = lastExecuteTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.last_finish_time_utc
     *
     * @return the value of lt_schedule_job.last_finish_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getLastFinishTimeUtc() {
        return lastFinishTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.last_finish_time_utc
     *
     * @param lastFinishTimeUtc the value for lt_schedule_job.last_finish_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setLastFinishTimeUtc(Integer lastFinishTimeUtc) {
        this.lastFinishTimeUtc = lastFinishTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.next_execute_time_utc
     *
     * @return the value of lt_schedule_job.next_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getNextExecuteTimeUtc() {
        return nextExecuteTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.next_execute_time_utc
     *
     * @param nextExecuteTimeUtc the value for lt_schedule_job.next_execute_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setNextExecuteTimeUtc(Integer nextExecuteTimeUtc) {
        this.nextExecuteTimeUtc = nextExecuteTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.crontab
     *
     * @return the value of lt_schedule_job.crontab
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getCrontab() {
        return crontab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.crontab
     *
     * @param crontab the value for lt_schedule_job.crontab
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCrontab(String crontab) {
        this.crontab = crontab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.type
     *
     * @return the value of lt_schedule_job.type
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.type
     *
     * @param type the value for lt_schedule_job.type
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_schedule_job.params
     *
     * @return the value of lt_schedule_job.params
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_schedule_job.params
     *
     * @param params the value for lt_schedule_job.params
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setParams(String params) {
        this.params = params;
    }
}