package com.lt.dao.model;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.ebay_api_key_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebayApiKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.HardExpirationTime
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer hardexpirationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.ebay_site_code
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer ebaySiteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.last_listing_sync_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer lastListingSyncTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private Integer updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_store.ebay_token
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    private String ebayToken;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.id
     *
     * @return the value of lt_store.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.id
     *
     * @param id the value for lt_store.id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.name
     *
     * @return the value of lt_store.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.name
     *
     * @param name the value for lt_store.name
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.platform
     *
     * @return the value of lt_store.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.platform
     *
     * @param platform the value for lt_store.platform
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.is_active
     *
     * @return the value of lt_store.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.is_active
     *
     * @param isActive the value for lt_store.is_active
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.company_id
     *
     * @return the value of lt_store.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.company_id
     *
     * @param companyId the value for lt_store.company_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.ebay_api_key_id
     *
     * @return the value of lt_store.ebay_api_key_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbayApiKeyId() {
        return ebayApiKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.ebay_api_key_id
     *
     * @param ebayApiKeyId the value for lt_store.ebay_api_key_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayApiKeyId(Integer ebayApiKeyId) {
        this.ebayApiKeyId = ebayApiKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.HardExpirationTime
     *
     * @return the value of lt_store.HardExpirationTime
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getHardexpirationtime() {
        return hardexpirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.HardExpirationTime
     *
     * @param hardexpirationtime the value for lt_store.HardExpirationTime
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setHardexpirationtime(Integer hardexpirationtime) {
        this.hardexpirationtime = hardexpirationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.ebay_site_code
     *
     * @return the value of lt_store.ebay_site_code
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getEbaySiteCode() {
        return ebaySiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.ebay_site_code
     *
     * @param ebaySiteCode the value for lt_store.ebay_site_code
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbaySiteCode(Integer ebaySiteCode) {
        this.ebaySiteCode = ebaySiteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.last_listing_sync_time_utc
     *
     * @return the value of lt_store.last_listing_sync_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getLastListingSyncTimeUtc() {
        return lastListingSyncTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.last_listing_sync_time_utc
     *
     * @param lastListingSyncTimeUtc the value for lt_store.last_listing_sync_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setLastListingSyncTimeUtc(Integer lastListingSyncTimeUtc) {
        this.lastListingSyncTimeUtc = lastListingSyncTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.create_time_utc
     *
     * @return the value of lt_store.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.create_time_utc
     *
     * @param createTimeUtc the value for lt_store.create_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.create_user_id
     *
     * @return the value of lt_store.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.create_user_id
     *
     * @param createUserId the value for lt_store.create_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.update_time_utc
     *
     * @return the value of lt_store.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.update_time_utc
     *
     * @param updateTimeUtc the value for lt_store.update_time_utc
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.update_user_id
     *
     * @return the value of lt_store.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.update_user_id
     *
     * @param updateUserId the value for lt_store.update_user_id
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_store.ebay_token
     *
     * @return the value of lt_store.ebay_token
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public String getEbayToken() {
        return ebayToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_store.ebay_token
     *
     * @param ebayToken the value for lt_store.ebay_token
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    public void setEbayToken(String ebayToken) {
        this.ebayToken = ebayToken;
    }
}