package com.lt.dao.model;

public class TrackingTagJobErrorDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.tracking_tag_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private Integer trackingTagJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.step
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private Integer step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.ebay_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private String ebayJobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.ebay_down_file_ref_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private String ebayDownFileRefId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_tracking_tag_job_error_detail.error_message
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    private String errorMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.id
     *
     * @return the value of lt_tracking_tag_job_error_detail.id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.id
     *
     * @param id the value for lt_tracking_tag_job_error_detail.id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.tracking_tag_job_id
     *
     * @return the value of lt_tracking_tag_job_error_detail.tracking_tag_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public Integer getTrackingTagJobId() {
        return trackingTagJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.tracking_tag_job_id
     *
     * @param trackingTagJobId the value for lt_tracking_tag_job_error_detail.tracking_tag_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setTrackingTagJobId(Integer trackingTagJobId) {
        this.trackingTagJobId = trackingTagJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.step
     *
     * @return the value of lt_tracking_tag_job_error_detail.step
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.step
     *
     * @param step the value for lt_tracking_tag_job_error_detail.step
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setStep(Integer step) {
        this.step = step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.ebay_job_id
     *
     * @return the value of lt_tracking_tag_job_error_detail.ebay_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public String getEbayJobId() {
        return ebayJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.ebay_job_id
     *
     * @param ebayJobId the value for lt_tracking_tag_job_error_detail.ebay_job_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setEbayJobId(String ebayJobId) {
        this.ebayJobId = ebayJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.ebay_down_file_ref_id
     *
     * @return the value of lt_tracking_tag_job_error_detail.ebay_down_file_ref_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public String getEbayDownFileRefId() {
        return ebayDownFileRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.ebay_down_file_ref_id
     *
     * @param ebayDownFileRefId the value for lt_tracking_tag_job_error_detail.ebay_down_file_ref_id
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setEbayDownFileRefId(String ebayDownFileRefId) {
        this.ebayDownFileRefId = ebayDownFileRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_tracking_tag_job_error_detail.error_message
     *
     * @return the value of lt_tracking_tag_job_error_detail.error_message
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_tracking_tag_job_error_detail.error_message
     *
     * @param errorMessage the value for lt_tracking_tag_job_error_detail.error_message
     *
     * @mbggenerated Tue Jun 30 18:54:59 CST 2015
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}