package com.lt.dao.model;

public class TransactionAccessToken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.access_token
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.lift_cycle
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private Long liftCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.enabled
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.create_time_utc
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_access_token.create_user_id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    private Integer createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.id
     *
     * @return the value of lt_transaction_access_token.id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.id
     *
     * @param id the value for lt_transaction_access_token.id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.access_token
     *
     * @return the value of lt_transaction_access_token.access_token
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.access_token
     *
     * @param accessToken the value for lt_transaction_access_token.access_token
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.lift_cycle
     *
     * @return the value of lt_transaction_access_token.lift_cycle
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public Long getLiftCycle() {
        return liftCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.lift_cycle
     *
     * @param liftCycle the value for lt_transaction_access_token.lift_cycle
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setLiftCycle(Long liftCycle) {
        this.liftCycle = liftCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.enabled
     *
     * @return the value of lt_transaction_access_token.enabled
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.enabled
     *
     * @param enabled the value for lt_transaction_access_token.enabled
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.create_time_utc
     *
     * @return the value of lt_transaction_access_token.create_time_utc
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.create_time_utc
     *
     * @param createTimeUtc the value for lt_transaction_access_token.create_time_utc
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_access_token.create_user_id
     *
     * @return the value of lt_transaction_access_token.create_user_id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_access_token.create_user_id
     *
     * @param createUserId the value for lt_transaction_access_token.create_user_id
     *
     * @mbggenerated Mon Mar 30 14:27:34 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }
}