package com.lt.dao.model;

import java.math.BigDecimal;

public class TransactionDetail {
	private String refDate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.transaciton_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer transacitonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.ref_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.ref_object
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private String refObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.amount
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.charge_date_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer chargeDateUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.create_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer createTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.create_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.update_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer updateTimeUtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_transaction_detail.update_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    private Integer updateUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.id
     *
     * @return the value of lt_transaction_detail.id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.id
     *
     * @param id the value for lt_transaction_detail.id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.transaciton_id
     *
     * @return the value of lt_transaction_detail.transaciton_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getTransacitonId() {
        return transacitonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.transaciton_id
     *
     * @param transacitonId the value for lt_transaction_detail.transaciton_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setTransacitonId(Integer transacitonId) {
        this.transacitonId = transacitonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.ref_id
     *
     * @return the value of lt_transaction_detail.ref_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.ref_id
     *
     * @param refId the value for lt_transaction_detail.ref_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.ref_object
     *
     * @return the value of lt_transaction_detail.ref_object
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public String getRefObject() {
        return refObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.ref_object
     *
     * @param refObject the value for lt_transaction_detail.ref_object
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setRefObject(String refObject) {
        this.refObject = refObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.amount
     *
     * @return the value of lt_transaction_detail.amount
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.amount
     *
     * @param amount the value for lt_transaction_detail.amount
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.charge_date_utc
     *
     * @return the value of lt_transaction_detail.charge_date_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getChargeDateUtc() {
        return chargeDateUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.charge_date_utc
     *
     * @param chargeDateUtc the value for lt_transaction_detail.charge_date_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setChargeDateUtc(Integer chargeDateUtc) {
        this.chargeDateUtc = chargeDateUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.create_time_utc
     *
     * @return the value of lt_transaction_detail.create_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getCreateTimeUtc() {
        return createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.create_time_utc
     *
     * @param createTimeUtc the value for lt_transaction_detail.create_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setCreateTimeUtc(Integer createTimeUtc) {
        this.createTimeUtc = createTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.create_user_id
     *
     * @return the value of lt_transaction_detail.create_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.create_user_id
     *
     * @param createUserId the value for lt_transaction_detail.create_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.update_time_utc
     *
     * @return the value of lt_transaction_detail.update_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getUpdateTimeUtc() {
        return updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.update_time_utc
     *
     * @param updateTimeUtc the value for lt_transaction_detail.update_time_utc
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setUpdateTimeUtc(Integer updateTimeUtc) {
        this.updateTimeUtc = updateTimeUtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_transaction_detail.update_user_id
     *
     * @return the value of lt_transaction_detail.update_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_transaction_detail.update_user_id
     *
     * @param updateUserId the value for lt_transaction_detail.update_user_id
     *
     * @mbggenerated Mon Apr 27 14:11:43 CST 2015
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

	public String getRefDate()
	{
		return refDate;
	}

	public void setRefDate(String refDate)
	{
		this.refDate = refDate;
	}
}