package com.lt.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.AdAdvertiseVariation;
import com.lt.dao.po.AdAdvertiseVariationPO;
@Repository
public interface AdAdvertiseVariationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int insert(AdAdvertiseVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int insertSelective(AdAdvertiseVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    AdAdvertiseVariation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKeySelective(AdAdvertiseVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AdAdvertiseVariation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_variation
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKey(AdAdvertiseVariation record);
    
    List<AdAdvertiseVariationPO> getAdVariationList(AdAdvertiseVariationPO po);
    int updateAdVariationByAdId(AdAdvertiseVariationPO po);
}