package com.lt.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.AdAdvertiseFeed;
import com.lt.dao.po.AdAdvertiseFeedPO;
@Repository
public interface AdAdvertiseFeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int insert(AdAdvertiseFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int insertSelective(AdAdvertiseFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    AdAdvertiseFeed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKeySelective(AdAdvertiseFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AdAdvertiseFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_advertise_feed
     *
     * @mbggenerated Mon May 04 11:11:12 CST 2015
     */
    int updateByPrimaryKey(AdAdvertiseFeed record);
    
    List<AdAdvertiseFeedPO> getAdFeedList(AdAdvertiseFeedPO po);
}