package com.lt.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.lt.dao.model.AdCampaign;
import com.lt.dao.po.AdCampaignPO;
@Repository
public interface AdCampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int insert(AdCampaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int insertSelective(AdCampaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    AdCampaign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int updateByPrimaryKeySelective(AdCampaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AdCampaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    int updateByPrimaryKey(AdCampaign record);
    
    //自定义
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_campaign
     *
     * @mbggenerated Mon Apr 13 18:46:40 CST 2015
     */
    List<AdCampaignPO> selectSelective(AdCampaignPO adCampaignPO);
    
    List<AdCampaignPO> getCampaignList(AdCampaignPO po);
    Integer checkExist(@Param("name")String name);
    Integer getLastInsertId();
}