package com.lt.dao.mapper;

import java.util.Date;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.AdGoogleAdwordsReportCampaignTemp;
import com.lt.dao.model.AdGoogleAdwordsReportCampaignTempWithBLOBs;
import com.lt.dao.po.AdGoogleAdwordsReportCampaignTempPO;
@Repository
public interface AdGoogleAdwordsReportCampaignTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_campaign_temp
     *
     * @mbggenerated Tue Apr 28 11:34:17 CST 2015
     */
    int insert(AdGoogleAdwordsReportCampaignTempWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_campaign_temp
     *
     * @mbggenerated Tue Apr 28 11:34:17 CST 2015
     */
    int insertSelective(AdGoogleAdwordsReportCampaignTempWithBLOBs record);
    
    //自定义
    /**
     * 根据时间将当天报表数据同步至临时表
     * @param date
     */
    void syncByGoogleAdwordsReportCampaign(Date date);
    /**
     * 根据时间删除当天数据
     * @param date
     */
    void delete(Date date);
    /**
     * 根据条件查询临时表数据
     * @param adGoogleAdwordsReportCampaignTempPO
     * @return
     */
    List<AdGoogleAdwordsReportCampaignTemp> selectByCampaign(AdGoogleAdwordsReportCampaignTempPO adGoogleAdwordsReportCampaignTempPO);
    /**
     * 根据条件修改临时表数据
     * @param adGoogleAdwordsReportCampaignTemp
     */
    void updateByClicks(AdGoogleAdwordsReportCampaignTemp adGoogleAdwordsReportCampaignTemp);
}