package com.lt.dao.mapper;

import java.util.Date;
import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.AdGoogleAdwordsReportAd;
import com.lt.dao.model.AdGoogleAdwordsReportAdWithBLOBs;
@Repository
public interface AdGoogleAdwordsReportAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int deleteByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int insert(AdGoogleAdwordsReportAdWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int insertSelective(AdGoogleAdwordsReportAdWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    AdGoogleAdwordsReportAdWithBLOBs selectByPrimaryKey(Integer pkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int updateByPrimaryKeySelective(AdGoogleAdwordsReportAdWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(AdGoogleAdwordsReportAdWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ad_google_adwords_report_ad
     *
     * @mbggenerated Mon Apr 27 11:55:29 CST 2015
     */
    int updateByPrimaryKey(AdGoogleAdwordsReportAd record);
    
    //自定义
    void syncByGoogleAdwordsReportAd(Date date);
    
    List<AdGoogleAdwordsReportAd> selectByAdId(AdGoogleAdwordsReportAd adGoogleAdwordsReportAd);
    
    void updateSelective(AdGoogleAdwordsReportAd adGoogleAdwordsReportAd);
}