package com.lt.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.EbayListing;
import com.lt.dao.po.EbayListingPO;
import com.lt.dao.po.TrackingTagPO;
@Repository
public interface EbayListingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(EbayListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(EbayListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    EbayListing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EbayListing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_listing
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(EbayListing record);
    
    //自定义
    /**
     * 根据条件查询EbayListing集合
     * @param ebayListingPO
     * @return
     */
    List<EbayListingPO> selectSelectiveByPage(TrackingTagPO trackingTag);
    
    /**
     * 根据条件查询EbayListing总数
     * @param ebayListingPO
     * @return
     */
    Integer countSelective(TrackingTagPO trackingTag);
    
    /**
     * 查询门店下的所有站点（site id）
     * @param storeId
     * @return
     */
    List<Integer> selectSiteIdByStore(Integer storeId);

    List<EbayListingPO> selectSiteByCompanyAndStore(EbayListingPO ebayListingPO);
    
    String selectGaTrackingIdByEbayListingId(String ebayListingId);
    
}