package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.EbayCategoryFeatureDefinitionAndDefault;
@Repository
public interface EbayCategoryFeatureDefinitionAndDefaultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(EbayCategoryFeatureDefinitionAndDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(EbayCategoryFeatureDefinitionAndDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    EbayCategoryFeatureDefinitionAndDefault selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EbayCategoryFeatureDefinitionAndDefault record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_category_feature_definition_and_default
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(EbayCategoryFeatureDefinitionAndDefault record);
}