package com.lt.dao.mapper;

import com.lt.dao.model.EbayPrefetchVarchar;

public interface EbayPrefetchVarcharMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(EbayPrefetchVarchar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(EbayPrefetchVarchar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    EbayPrefetchVarchar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EbayPrefetchVarchar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ebay_prefetch_varchar
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(EbayPrefetchVarchar record);
}