package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.FacebookReportCampaign;
@Repository
public interface FacebookReportCampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_facebook_report_campaign
     *
     * @mbggenerated Thu Aug 20 11:43:02 CST 2015
     */
    int insert(FacebookReportCampaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_facebook_report_campaign
     *
     * @mbggenerated Thu Aug 20 11:43:02 CST 2015
     */
    int insertSelective(FacebookReportCampaign record);
}