package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsReportAutomaticPlacements;

@Repository
public interface GoogleAdwordsReportAutomaticPlacementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_automatic_placements
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insert(GoogleAdwordsReportAutomaticPlacements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_automatic_placements
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insertSelective(GoogleAdwordsReportAutomaticPlacements record);
    int deleteByDate(java.util.Date date);
    
}