package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAnalyticsReportAudienceOverview;

@Repository
public interface GoogleAnalyticsReportAudienceOverviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_analytics_report_audience_overview
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    int insert(GoogleAnalyticsReportAudienceOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_analytics_report_audience_overview
     *
     * @mbggenerated Wed Jul 08 17:48:13 CST 2015
     */
    int insertSelective(GoogleAnalyticsReportAudienceOverview record);

    int deleteByDate(java.util.Date date);
}