package com.lt.dao.mapper;

import com.lt.dao.model.GoogleAdwordsReportAdGroup;
import com.lt.dao.model.GoogleAdwordsReportAdGroupWithBLOBs;


import org.springframework.stereotype.Repository;

@Repository
public interface GoogleAdwordsReportAdGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_ad_group
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insert(GoogleAdwordsReportAdGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_ad_group
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insertSelective(GoogleAdwordsReportAdGroupWithBLOBs record);
    
    
    /**
     * 验证该记录是否存在
     * @param record
     * @return 主键ID
     */
    Integer checkExist(GoogleAdwordsReportAdGroup record);
    int deleteByDate(java.util.Date date);
}