package com.lt.dao.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsReportCampaign;
import com.lt.dao.model.GoogleAdwordsReportCampaignWithBLOBs;

@Repository
public interface GoogleAdwordsReportCampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_campaign
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insert(GoogleAdwordsReportCampaignWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_campaign
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insertSelective(GoogleAdwordsReportCampaignWithBLOBs record);
    
    /**
     * 验证该记录是否存在
     * @param record
     * @return 主键ID
     */
    Integer checkExist(GoogleAdwordsReportCampaignWithBLOBs record);
  
    int deleteByDate(java.util.Date date);
    
}