package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsAdGroup;
import com.lt.dao.model.GoogleAdwordsAdGroupWithBLOBs;
@Repository
public interface GoogleAdwordsAdGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insert(GoogleAdwordsAdGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insertSelective(GoogleAdwordsAdGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    GoogleAdwordsAdGroupWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeySelective(GoogleAdwordsAdGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(GoogleAdwordsAdGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKey(GoogleAdwordsAdGroup record);
}