package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsReportPlacement;
import com.lt.dao.model.GoogleAdwordsReportPlacementWithBLOBs;

@Repository
public interface GoogleAdwordsReportPlacementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_placement
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insert(GoogleAdwordsReportPlacementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_report_placement
     *
     * @mbggenerated Sun Apr 26 09:45:03 CST 2015
     */
    int insertSelective(GoogleAdwordsReportPlacementWithBLOBs record);
    
    /**
     * 验证该记录是否存在
     * @param record
     * @return 主键ID
     */
    Integer checkExist(GoogleAdwordsReportPlacement record);
    int deleteByDate(java.util.Date date);
    
}