package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsCampaignCriterion;
import com.lt.dao.model.GoogleAdwordsCampaignCriterionWithBLOBs;
@Repository
public interface GoogleAdwordsCampaignCriterionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insert(GoogleAdwordsCampaignCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insertSelective(GoogleAdwordsCampaignCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    GoogleAdwordsCampaignCriterionWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeySelective(GoogleAdwordsCampaignCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(GoogleAdwordsCampaignCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_campaign_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKey(GoogleAdwordsCampaignCriterion record);
}