package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.GoogleAdwordsAdGroupCriterion;
import com.lt.dao.model.GoogleAdwordsAdGroupCriterionWithBLOBs;
@Repository
public interface GoogleAdwordsAdGroupCriterionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insert(GoogleAdwordsAdGroupCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int insertSelective(GoogleAdwordsAdGroupCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    GoogleAdwordsAdGroupCriterionWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeySelective(GoogleAdwordsAdGroupCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(GoogleAdwordsAdGroupCriterionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_google_adwords_ad_group_criterion
     *
     * @mbggenerated Wed Apr 22 11:31:17 CST 2015
     */
    int updateByPrimaryKey(GoogleAdwordsAdGroupCriterion record);
}