package com.lt.dao.mapper;

import com.lt.dao.model.PictureFolder;

public interface PictureFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(PictureFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(PictureFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    PictureFolder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PictureFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_picture_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(PictureFolder record);
}