package com.lt.dao.mapper;

import com.lt.dao.model.ProductFolder;

public interface ProductFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(ProductFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(ProductFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    ProductFolder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProductFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_product_folder
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(ProductFolder record);
}