package com.lt.dao.mapper;

import com.lt.dao.model.SessionAdmin;

public interface SessionAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(SessionAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(SessionAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    SessionAdmin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(SessionAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(SessionAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_session_admin
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(SessionAdmin record);
}