package com.lt.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.lt.dao.model.Store;
import com.lt.dao.po.StorePO;

@Repository
public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int insertSelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKeyWithBLOBs(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_store
     *
     * @mbggenerated Tue Mar 17 14:35:43 GMT+08:00 2015
     */
    int updateByPrimaryKey(Store record);
    
    /**
     *  ebay api auth entity store
     * @param companyId
     * @param storeId
     * @return
     */
    Map<String,Object> selectAuthStore(@Param("companyId")String companyId,@Param("storeId")String storeId);
    
    /**
     * 查询公司下的门店
     * @param companyId
     * @return
     */
    List<Store> selectSelective(@Param("companyId")Integer companyId, @Param("storeId")Integer storeId);
    
    /**
     * 查询公司下的门店
     * @param companyId
     * @return
     */
    List<Store> getPlatforms(Integer storeId);
    
    /**
     * 查询公司下的门店
     * @param companyId
     * @return
     */
    List<Store> getStores(Store record);
    
    /**
     * 根据门店id 查询门店相关信息及门店绑定的ebay api key
     * @param id
     * @return
     */
    StorePO getStoreAndApiKey(Integer id);
}