package com.lt.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.lt.dao.model.TrackingTagJob;
import com.lt.dao.po.TrackingTagJobPO;
@Repository
public interface TrackingTagJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    int insert(TrackingTagJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    int insertSelective(TrackingTagJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    TrackingTagJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    int updateByPrimaryKeySelective(TrackingTagJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_tracking_tag_job
     *
     * @mbggenerated Sat Jun 27 22:43:37 CST 2015
     */
    int updateByPrimaryKey(TrackingTagJob record);
    
    //自定义
    List<TrackingTagJobPO> searchByIsStart(@Param("isStart")Boolean isStart);
}