package com.lt.dao.mapper;

import org.springframework.stereotype.Repository;

import com.lt.dao.model.TransactionPaypalAccount;
@Repository
public interface TransactionPaypalAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    int insert(TransactionPaypalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    int insertSelective(TransactionPaypalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    TransactionPaypalAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    int updateByPrimaryKeySelective(TransactionPaypalAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_transaction_payment_account
     *
     * @mbggenerated Tue Mar 24 15:09:44 CST 2015
     */
    int updateByPrimaryKey(TransactionPaypalAccount record);
    
    //by jameschen
    TransactionPaypalAccount selectByTransactionId(Integer id);
}